version: 1
disable_existing_loggers: False
formatters:
  simple_fmt:
    format: '%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple_fmt
    stream: ext://sys.stdout
  fileHandler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple_fmt
    filename: logdump/logger.log
loggers:
  __main__:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: no
root:
  level: DEBUG
disable_existing_loggers: False